more work on building manga info page

diff --git a/karat-cli b/karat-cli
--- a/karat-cli
+++ b/karat-cli
@@ -9,30 +9,44 @@ RSS_DIR:=feeds
 OUT_DIR:=manga
 TEMPLATE_DIR:=templates
 
+MANGA_LIST=$(subst .content.html,,$(shell ls $(CONTENT_DIR)))
+
 .PHONY: help init build clean new-manga new-chapter
 
 help:
 	@echo 'karat-cli help|build|clean|new-manga|new-chapter'
 
+# prob dont need this one
 init:
-	@echo "init"
+	@echo "initializing directories"
 
-build:
-	@for manga in ${CONTENT_DIR}/*; do \
-		cat "${manga}"; \
-	done
+build: $(OUT_DIR)/$(addsuffix .html,$(MANGA_LIST))
 
 new-manga:
-	@if [ -z "${name}" ]; then \
-		echo "Missing name field."; \
-		exit 1; \
-	fi
-	@echo "Creating new manga page for '${name}'"
-	@# todo, sanitize name first
-	@cp "${TEMPLATE_DIR}/mangainfo.template.html" "${OUT_DIR}/${name}.html"
+	@if [ -z "$(name)" ]; then \
+		echo "Missing name field."; exit 1; \
+	fi; \
+	echo "Creating new manga page for '$(name)'"; \
+	KS_MANGATITLE="$(name)"; export KS_MANGATITLE; \
+	content_file="$(CONTENT_DIR)/$$KS_MANGATITLE.content.html"; \
+	envsubst < "$(TEMPLATE_DIR)/mangainfo.template.html" > "$$content_file"; \
+	"$$EDITOR" "$$content_file"; \
+	echo "Once you are satisfied with your changes, you can rebuild to generate the html page."
+
+new-chapter:
+	@echo "new chapter"
 
 clean:
-	@echo "clean"
+	@# ask user for confirm here
+	@echo "cleaning..."; \
+	rm $(OUT_DIR)/*
+
+$(OUT_DIR)/%.html: $(CONTENT_DIR)/%.content.html
+	@echo "building manga page: $@";\
+	KS_MANGATITLE=$(notdir $(basename $@)); export KS_MANGATITLE; \
+	envsubst < $(TEMPLATE_DIR)/head.html >> "$@"; \
+	cat "$^" >> "$@"; \
+	cat $(TEMPLATE_DIR)/foot.html >> "$@"
 
 # $(RSS_DIR)/%.xml:
 # 	@echo "feeds"
